device_list_name: RLC-823A 16X

ipc:
  display:
    desc: 设置>显示

    items:
      display:
        date:
          desc: 设置>显示>日期
          name: 日期
          options:
          - 隐藏
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下

        day_and_night:
          black_and_white:
            desc: 白天和黑夜>黑白
            name: 黑白
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 黑白
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          day_color:
            desc: 白天和黑夜>白天彩色
            name: 白天彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 白天彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          desc: 白天和黑夜
          mode_switching:
            desc: 白天和黑夜>模式切换
            name: 模式切换
            options:
            - 黑白
            - 彩色
            - 自动
            - 日夜切换阈值
            text:
            - 模式切换
            - 黑白
            - 彩色
            - 自动
            - 光线较亮时自动显示彩色，较暗时自动显示黑白。
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - '0'
            - '100'
            type: popup
          name: 白天和黑夜
          options:
          - 模式切换
          - 黑白
          - 白天彩色
          text:
          - 白天和黑夜
          - 模式切换
          - 高光/阴影调节
          - 黑白
          - 白天彩色
          type: popup

        auto_zoom:
          name: 自动对焦

        device_name:
          desc: 设置>显示>设备名称
          name: 设备名称
          options:
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏

        horizontal_flip:
          desc: 设置>显示>水平翻转
          name: 水平翻转
          options:
          - switch_on
          - switch_off
          type: switch

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true
          night_vision_zoom_enhance: true

        motion_mark:
          desc: 设置>显示>移动标记
          name: 移动标记
          options:
          - switch-on
          - switch-off
          text:
          - 移动标记
          - 画面为清晰时，智能检测到移动事物将进行标记。
          type: switch

        options:
        - 垂直翻转
        - 水平翻转
        - 码流
        - 设备名称
        - 日期
        - 水印
        - 图像设置
        - 白天和黑夜
        - 自动对焦
        - 遮盖区域

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 4

        stream:
          clear:
            frame_rate:
              desc: 设置>显示>码流>码流>清晰>帧率(FPS)
              name: 帧率(FPS)
              options:
              - 25(默认)
              - '22'
              - '20'
              - '18'
              - '16'
              - '15'
              - '12'
              - '10'
            i_frame_interval:
              desc: 设置>显示>码流>码流>清晰>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x

            max_bit_rate:
              desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
              name: 最大码率(Kbps)
              options:
              - '4096'
              - '5120'
              - 6144(默认)
              - '7168'
              - '8192'


            resolution:
              desc: 设置>显示>码流>码流>清晰>分辨率
              name: 分辨率
              options:
              - 3840*2160
              - 2560*1440
              - 2304*1296

            text:
              - I 帧间隔

          fluent:
            frame_rate:
              desc: 设置>显示>码流>码流>流畅>帧率(FPS)
              name: 帧率(FPS)
              options:
              - '15'
              - 10(默认)
              - '7'
              - '4'
            i_frame_interval:
              desc: 设置>显示>码流>码流>流畅>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
              - 3x
              - 4x

            max_bit_rate:
              desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
              options:
              - '64'
              - '128'
              - '160'
              - '192'
              - 256(默认)
              - '384'
              - '512'

            resolution:
              desc: 设置>显示>码流>码流>流畅>分辨率
              name: 分辨率
              options:
              - 640*360

            text:
             - I 帧间隔

          frame_rate_mode:
            name: '帧率控制(A代表自动，B代表恒定，C代表逐步)'
            desc: '设置>显示>码流>码流>帧率控制'
            support_mode: 'ABC'

          text:
            - I 帧间隔
          options:
            - '帧率控制'

        text:
          - 垂直翻转
          - 水平翻转
          - 码流
          - 设备名称
          - 日期
          - 水印
          - 图像设置
          - 白天和黑夜
          - 自动对焦
          - 设备在断电重启后会自动对焦一次。
          - 遮盖区域

        vertical_flip: 垂直翻转
        watermark: 水印

uid: 952700Y001GD1VAV
