# 安卓测试手机的识别码：28131FDH2000K1   VOA6AU89B6GAO7U4  RFCX118N25P
# iPhone测试手机识别码：3db17f31334a5dbbe98c6d03b110f9ae0115e352
# 00008101-001E6C623ED0001E
config_device_sn: RFCX118N25P

# 被测app包名
# 安卓：com.mcu.reolink
# iOS：com.reo.link
config_apk_name: com.mcu.reolink

# 需要安装的app安装包存放位置
apk_local_path: "H:\\app-uiauto-test-dev\\apk_pkgs\\Android-Reolink-P2PCN-4.45.0.2.20240506--release.apk"

# wda包名：
wda_bundle_id: com.facebook.WebDriverAgentRunner.reo.xctrunner