device_list_name: CX410
uid: 952700Y005K15KA1

ipc:
  display:
    items:
      display:
        text:
          - 垂直翻转
          - 水平翻转
          - 码流
          - 移动标记
          - 画面为清晰时，智能检测到移动事物将进行标记。
          - 设备名称
          - 日期
          - 水印
          - 图像设置
          - 白天和黑夜
          - 遮盖区域
        options:
          - 垂直翻转
          - 水平翻转
          - 码流
          - 移动标记
          - 设备名称
          - 日期
          - 水印
          - 图像设置
          - 白天和黑夜
          - 遮盖区域

        date: '日期(无需配置，有则保留无则删除)'

        day_and_night:
          day_color:
            desc: 白天和黑夜>白天彩色
            name: 白天彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 白天彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          desc: 白天和黑夜
          mode_switching:
            desc: 白天和黑夜>模式切换
            name: 模式切换
            options:
            - 黑白
            - 彩色
            - 自动
            - 日夜切换阈值
            text:
            - 模式切换
            - 黑白
            - 彩色
            - 自动
            - 光线较亮时自动显示彩色，较暗时自动显示黑白。
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - '0'
            - '100'
            type: popup
          name: 白天和黑夜
          night_vision_color:
            desc: 白天和黑夜>夜视彩色
            name: 夜视彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 夜视彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          options:
          - 模式切换
          - 白天彩色
          - 夜视彩色
          text:
          - 白天和黑夜
          - 模式切换
          - 高光/阴影调节
          - 白天彩色
          - 夜视彩色
          type: popup

        device_name: '设备名称(无需配置，有则保留无则删除)'

        image_setting:
          anti_flicker: true
          brightness: '亮度'
          brightness_sync: true
          contrast: 对比度
          hdr: true
          night_transparent_vision: false
          saturation: 饱和度
          sharpness: 锐度

        motion_mark: '移动标记(无需配置，有则保留无则删除)'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 4

        stream:
          text:
            - I 帧间隔
            - 帧率控制
          options:
            - 帧率控制

          clear:
            text:
              - I 帧间隔

            frame_rate:
              desc: 设置>显示>码流>码流>清晰>帧率(FPS)
              name: 帧率(FPS)
              options:
              - '30'
              - 25(默认)
              - '22'
              - '20'
              - '18'
              - '16'
              - '15'
              - '12'

            i_frame_interval:
              desc: 设置>显示>码流>码流>清晰>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x

            max_bit_rate:
              name: 最大码率(Kbps)
              options:
              - '2048'
              - '3072'
              - '4096'
              - 5120(默认)
              - '6144'

            resolution:
              desc: 设置>显示>码流>码流>清晰>分辨率
              name: 分辨率
              options:
              - 2560*1440
              - 1920*1080

          fluent:
            text:
              - I 帧间隔

            frame_rate:
              desc: 设置>显示>码流>码流>流畅>帧率(FPS)
              name: 帧率(FPS)
              options:
              - '15'
              - 10(默认)
              - '7'
              - '4'

            i_frame_interval:
              desc: 设置>显示>码流>码流>流畅>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
              - 3x
              - 4x

            max_bit_rate:
              desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
              options:
              - '64'
              - '128'
              - '160'
              - '192'
              - 256(默认)
              - '384'
              - '512'

            resolution:
              desc: 设置>显示>码流>码流>流畅>分辨率
              name: 分辨率
              options:
              - 640*360


            frame_rate_mode:
              name: '帧率控制(A代表自动，B代表恒定，C代表逐步)'
              desc: '设置>显示>码流>码流>帧率控制'
              support_mode: 'ABC'


        horizontal_flip: '水平翻转(无需配置，有则保留无则删除)'
        vertical_flip: '垂直翻转(无需配置，有则保留无则删除)'
        watermark: '水印(无需配置，有则保留无则删除)'

